
name: Build Docs pages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
      - name: Hugo setup
        uses: peaceiris/actions-hugo@v2.4.12
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    
      - uses: actions/checkout@v3

      - name: Compile site
        run: hugo --source exampleSite --themesDir ../.. -d docs
        
      - name: Package
        uses: actions/upload-pages-artifact@v1.0.4
        with:
          path: example/docs
      
      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v1.0.10
        with:
          token: ${{ github.token }}
          page_url: /docs
